name: "validador_cpf"

environment:
  sdk: '^3.4.0'
dependencies:
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  meta: ^1.16.0
  test: ^1.25.8
dev_dependencies:
  coverage: ^1.11.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
